# Generated by Django 4.0.3 on 2023-08-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_prettynum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prettynum',
            old_name='statue',
            new_name='status',
        ),
    ]
