# Generated by Django 4.0.3 on 2024-01-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='titile',
            new_name='title',
        ),
    ]
